"""0001 initial

Revision ID: 607dcc264c76
Revises: 
Create Date: 2023-08-01 11:24:30.570980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607dcc264c76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('terms', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Numeric(), nullable=False),
    sa.Column('total_adjustments', sa.Numeric(), nullable=False),
    sa.Column('total_tax', sa.Numeric(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'open', 'paid', 'void', name='invoice_status'), nullable=False),
    sa.Column('template_module', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], name=op.f('fk_invoice_customer_customer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner'], ['customer.id'], name=op.f('fk_invoice_owner_customer'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice')),
    sa.UniqueConstraint('uuid', name=op.f('uq_invoice_uuid'))
    )
    op.create_table('payment',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('invoice', sa.Integer(), nullable=False),
    sa.Column('customer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], name=op.f('fk_payment_customer_customer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice'], ['invoice.id'], name=op.f('fk_payment_invoice_invoice'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('uuid', name=op.f('uq_payment_uuid'))
    )
    op.create_table('refund',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment'], ['payment.id'], name=op.f('fk_refund_payment_payment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund')),
    sa.UniqueConstraint('uuid', name=op.f('uq_refund_uuid'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund')
    op.drop_table('payment')
    op.drop_table('invoice')
    # ### end Alembic commands ###
